[package]
name = "apk-info"
description = "APK file parser"
license-file = "LICENSE"
version.workspace = true
edition.workspace = true

[lib]
name = "apk_info"
crate-type = ["cdylib"]

[dependencies]
axml.workspace = true
env_logger.workspace = true
pyo3.workspace = true
serde.workspace = true
serde_json.workspace = true
zip.workspace = true

[workspace]
resolver = "2"
members = ["zip"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
# self crates
axml = { path = "axml" }
zip = { path = "zip" }

bitflags = "2.9.4"
env_logger = "0.11.8"
flate2 = "1.1.4"
log = "0.4.28"
memchr = "2.7.6"
minidom = "0.17.0"
once_cell = "1.21.3"
pyo3 = "0.26.0"
quick-xml = "0.38.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
signer = { path = "signer" }
winnow = { version = "0.7.13", features = ["simd"] }
