[package]
name = "apk-info"
description = "APK file parser"
license-file = "LICENSE"
version.workspace = true
edition.workspace = true

[lib]
name = "apk_info"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.26.0"
zip.workspace = true

[workspace]
resolver = "2"
members = ["zip"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
zip = {path = "zip"}
flate2 = "1.1.4"
memchr = "2.7.6"
winnow = "0.7.13"
